### ISSUE TITLE
Simple instructions on how to get started?

### ISSUE THREAD

**Issue by gitressa** [jonathanfranks/d8migrate#1]
I just saw your [Drupal 8 Migrate: It's not rocket science...](https://2018.tcdrupal.org/session/drupal-8-migrate-its-not-rocket-science) presentation, it was really great, so thank you very much for giving it as well as sharing your presentation and installation here.

I just spent a few minutes getting it up and running, so perhaps some simple instructions on how to get started could be added to the README.md file, something like this?

# Download and import the project
```
git clone git@github.com:jonathanfranks/d8migrate
cd d8migrate/
lando start
composer require --update-no-dev 'drupal/config_suite'
composer update --with-dependencies -vvv
lando drush site-install --db-url=mysql://drupal8:drupal8@database/drupal8 --account-pass=admin -y

# remove conflicting shortcut configuration and import config
lando drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();';
lando drush en config_suite
lando drush config-import

# create one-time login
lando drush uli -l http://d8migrate.lndo.site

# migrate commands examples
lando drush migrate:status
lando drush migrate:import pdf
lando drush migrate:import --group=nasa
lando drush migrate:import --group=meteorites
```

**Comment by jonathanfranks** [comment]
Thanks for the request, and thanks for watching the presentation!

I updated some config and the README so this is easier to follow. I'm leaving Shortcut as it sits so we can import config without having to change any of that, and we don't need config_suite (I included resetting the system UUID in the instructions). 

We don't need the one-time login because we set the admin password during the si.
